name: Check if python, modules and venv available to run flow-migrate scripts.
on: 
 # Run only on manuual trigger
 workflow_dispatch:

# Variables defined
env:
 download_dir: "/tmp"
 anaconda_location: "/apps/anaconda"
 anaconda_bin_path: "/apps/anaconda/bin"
 conda_env: "nifi_reg_py_env"
 conda_packages: "python=3.9.12 pip=21.2.4"
 pip_modules: "nipyapi pip_search jproperties"
 repo: "subin-telus/nifi-registry-migrate-code-test"
 proxy: "http://webproxystatic-on.tsl.telus.com:8080"

jobs:
 
 Conda-Python-Pip-Modules:
  runs-on: self-hosted
  
  steps:
   
   - name: Checkout Repository
     uses: actions/checkout@v3
     with:
      repository: ${{ env.repo }}
      token: ${{ secrets.TOKEN }}
   
   - name: Check Conda Installation
     id: conda-version
     shell: bash
     run: |
      conda_ver="$(cond --version)"
      echo "::set-output name=conda_ver::$conda_ver"
      echo -e "${{ conda_ver }}"
     continue-on-error: true
