name: Check if python, modules and venv available to run flow-migrate scripts.
on: 
 # Run only on manuual trigger
 workflow_dispatch:

# Variables defined
env:
 download_dir: "/tmp"
 anaconda_location: "/apps/anaconda"
 anaconda_bin_path: "/apps/anaconda/bin"
 conda_env: "nifi_reg_py_env"
 conda_packages: "python=3.9.12 pip=21.2.4"
 pip_modules: "nipyapi pip_search jproperties"
 repo: "subin-telus/nifi-registry-migrate-code-test"
 proxy: "http://webproxystatic-on.tsl.telus.com:8080"

jobs:
 
 checkout_repo:
  runs-on: self-hosted
  steps:
   - name: Checkout Repository
     uses: actions/checkout@v3
     with:
      repository: ${{ env.repo }}
      token: ${{ secrets.TOKEN }}
 
 conda_installation:
  runs-on: self-hosted
  needs: [checkout_repo]
  steps:
   - name: Get Conda Version
     id: get-conda-version
     shell: bash
     run: |
      conda_ver="$(cond --version)"
      echo "::set-output name=conda_version::$conda_ver"
      ver_len="$(echo ${conda_ver} | wc -m)"
      echo "::set-output name=ver_length::$ver_len"
     continue-on-error: true
   - name: Check Conda Version
     if: steps.get-conda-version.outputs.ver_length <= 1
     run: |
      echo "the length is: ${{ steps.get-conda-version.outputs.ver_length }}"
      #sh anaconda_installer.sh
