name: Check ca cert


on:
 # Run only on manuual trigger
 workflow_dispatch:


# Variables defined
env:
  conda_env: "nifi_reg_py_env"
  pip_modules: "nipyapi pip_search jproperties"
  repo: "subin-telus/nifi-registry-migrate-code-test"
  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}


jobs:

  checkout_repo:
    runs-on: self-hosted
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.repo }}
          token: ${{ secrets.TOKEN }}

  check_ca_cert:
    runs-on: self-hosted
    needs: [checkout_repo]
    steps:
    
      - name: Get cacert
        shell: bash
        run: |
          cat ca_cert/TCSO-issuing-and-root-CA.crt
